services:

  postgres:
    image: postgres:16
    container_name: task-api-postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: task-api-backend
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/taskdb

  frontend:
    build: ./frontend
    container_name: task-api-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: